### ISSUE TITLE
Rejections inside notifications do not revert the tables state

### ISSUE THREAD

**Issue by benjiewheeler** [ProtonProtocol/vert#4]
### Description

Rejections in notifications do not revert the changed tables back to their initial values.

**Example**: when there's a `check(false, ...)` inside an atomicassets notification, the assets are not returned to the sender (i.e. the assets table state is not reverted back)

### Step To Reproduce

_Atomicassets contract is used to demonstrate_

1. Create a contract that listens on transfer notifications for some collection from atomicassets (and rejects them)

```cpp
[[eosio::on_notify("atomicassets::logtransfer")]]
void testcontract::handle_logtransfer(name from, name to, vector<uint64_t> asset_ids, string memo)
{
    check(false, "transfers are closed");
}
```

2. Send an asset from that collection from one account to another (alice -> bob)
3. Check the atomicassets table `assets` under the `alice` scope

### Current Behavior

The asset should still be in alice's inventory

### Expected Behavior

The asset stays in bob's inventory

**Comment by jafri** [comment]
@benjiewheeler could you kindly add a minimal repro repo / gist, would speed up the fix

**Comment by benjiewheeler** [comment]
@jafri I created this repo with a sample contract and a simple mocha test

https://github.com/benjiewheeler/vert-issue-repro

**Comment by jafri** [comment]
Try @proton/vert@0.3.21
